name: CI Github Pages

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 21 * * *" # 每天 UTC 21:00（对应北京时间早上 5 点）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Scripts
        run: |
          python python/ScrapyJaToCn.py
          python python/ScrapySkillDesp.py

      - name: Generate Build Time File
        run: |
          TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S %z' > public/build-time.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
